
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.Ai_docScalarFieldEnum = {
  id: 'id',
  docente_id: 'docente_id',
  asignatura_id: 'asignatura_id',
  tiempo_id: 'tiempo_id',
  aspecto_id: 'aspecto_id',
  conclusion: 'conclusion',
  conclusion_general: 'conclusion_general',
  fortalezas: 'fortalezas',
  debilidades: 'debilidades',
  fecha_actualizacion: 'fecha_actualizacion'
};

exports.Prisma.AsigScalarFieldEnum = {
  id: 'id',
  cod_asignatura: 'cod_asignatura',
  nombre_asignatura: 'nombre_asignatura',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.Asp_cfgScalarFieldEnum = {
  id: 'id',
  cfg_id: 'cfg_id',
  cfg_a_id: 'cfg_a_id',
  aspecto_id: 'aspecto_id',
  nombre: 'nombre',
  descripcion: 'descripcion',
  orden: 'orden',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.CtxScalarFieldEnum = {
  id: 'id',
  id_cfg: 'id_cfg',
  id_sed: 'id_sed',
  id_per: 'id_per',
  id_prog: 'id_prog',
  id_sem: 'id_sem',
  id_grup: 'id_grup',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.DocScalarFieldEnum = {
  id: 'id',
  documento_docente: 'documento_docente',
  nombre_docente: 'nombre_docente',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.EstScalarFieldEnum = {
  id: 'id',
  documento_estudiante: 'documento_estudiante',
  primer_nombre: 'primer_nombre',
  segundo_nombre: 'segundo_nombre',
  primer_apellido: 'primer_apellido',
  segundo_apellido: 'segundo_apellido',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.Eval_docScalarFieldEnum = {
  id: 'id',
  docente_id: 'docente_id',
  asignatura_id: 'asignatura_id',
  contexto_academico_id: 'contexto_academico_id',
  tiempo_id: 'tiempo_id',
  promedio_general: 'promedio_general',
  desviacion_general: 'desviacion_general',
  total_evaluaciones: 'total_evaluaciones',
  total_realizadas: 'total_realizadas',
  total_pendientes: 'total_pendientes',
  total_aspectos: 'total_aspectos',
  porcentaje_cumplimiento: 'porcentaje_cumplimiento',
  suma: 'suma',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.Eval_doc_aspScalarFieldEnum = {
  id: 'id',
  docente_id: 'docente_id',
  asignatura_id: 'asignatura_id',
  tiempo_id: 'tiempo_id',
  aspecto_id: 'aspecto_id',
  suma: 'suma',
  promedio: 'promedio',
  desviacion: 'desviacion',
  total_respuestas: 'total_respuestas',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.GrupScalarFieldEnum = {
  id_grupo: 'id_grupo',
  nombre: 'nombre'
};

exports.Prisma.Met_evalScalarFieldEnum = {
  id: 'id',
  contexto_academico_id: 'contexto_academico_id',
  tiempo_id: 'tiempo_id',
  total_evaluaciones: 'total_evaluaciones',
  total_realizadas: 'total_realizadas',
  total_evaluaciones_registradas: 'total_evaluaciones_registradas',
  total_pendientes: 'total_pendientes',
  total_estudiantes: 'total_estudiantes',
  total_estudiantes_registrados: 'total_estudiantes_registrados',
  total_estudiantes_pendientes: 'total_estudiantes_pendientes',
  total_docentes: 'total_docentes',
  total_docentes_pendientes: 'total_docentes_pendientes',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.PartScalarFieldEnum = {
  id: 'id',
  estudiante_id: 'estudiante_id',
  docente_id: 'docente_id',
  asignatura_id: 'asignatura_id',
  contexto_academico_id: 'contexto_academico_id',
  tiempo_id: 'tiempo_id',
  estado_evaluacion: 'estado_evaluacion',
  fecha_evaluacion: 'fecha_evaluacion',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.PerScalarFieldEnum = {
  id_periodo: 'id_periodo',
  nombre: 'nombre'
};

exports.Prisma.ProgScalarFieldEnum = {
  id_prog: 'id_prog',
  nombre: 'nombre'
};

exports.Prisma.Rank_docScalarFieldEnum = {
  id: 'id',
  docente_id: 'docente_id',
  total_evaluaciones: 'total_evaluaciones',
  total_evaluaciones_realizadas: 'total_evaluaciones_realizadas',
  promedio_general: 'promedio_general',
  total_aspectos_evaluados: 'total_aspectos_evaluados',
  porcentaje_cumplimiento: 'porcentaje_cumplimiento',
  ranking: 'ranking',
  fecha_actualizacion: 'fecha_actualizacion'
};

exports.Prisma.SedScalarFieldEnum = {
  id_sede: 'id_sede',
  nombre: 'nombre'
};

exports.Prisma.SemScalarFieldEnum = {
  id_sem: 'id_sem',
  nombre: 'nombre'
};

exports.Prisma.TmpScalarFieldEnum = {
  id: 'id',
  anio: 'anio',
  mes: 'mes',
  dia: 'dia',
  semana: 'semana',
  trimestre: 'trimestre',
  fecha: 'fecha',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.ai_docOrderByRelevanceFieldEnum = {
  conclusion: 'conclusion',
  conclusion_general: 'conclusion_general'
};

exports.Prisma.asigOrderByRelevanceFieldEnum = {
  cod_asignatura: 'cod_asignatura',
  nombre_asignatura: 'nombre_asignatura'
};

exports.Prisma.asp_cfgOrderByRelevanceFieldEnum = {
  nombre: 'nombre',
  descripcion: 'descripcion'
};

exports.Prisma.docOrderByRelevanceFieldEnum = {
  documento_docente: 'documento_docente',
  nombre_docente: 'nombre_docente'
};

exports.Prisma.estOrderByRelevanceFieldEnum = {
  documento_estudiante: 'documento_estudiante',
  primer_nombre: 'primer_nombre',
  segundo_nombre: 'segundo_nombre',
  primer_apellido: 'primer_apellido',
  segundo_apellido: 'segundo_apellido'
};

exports.Prisma.grupOrderByRelevanceFieldEnum = {
  nombre: 'nombre'
};

exports.Prisma.perOrderByRelevanceFieldEnum = {
  nombre: 'nombre'
};

exports.Prisma.progOrderByRelevanceFieldEnum = {
  nombre: 'nombre'
};

exports.Prisma.sedOrderByRelevanceFieldEnum = {
  nombre: 'nombre'
};

exports.Prisma.semOrderByRelevanceFieldEnum = {
  nombre: 'nombre'
};
exports.part_estado_evaluacion = exports.$Enums.part_estado_evaluacion = {
  PENDIENTE: 'PENDIENTE',
  COMPLETA: 'COMPLETA'
};

exports.Prisma.ModelName = {
  ai_doc: 'ai_doc',
  asig: 'asig',
  asp_cfg: 'asp_cfg',
  ctx: 'ctx',
  doc: 'doc',
  est: 'est',
  eval_doc: 'eval_doc',
  eval_doc_asp: 'eval_doc_asp',
  grup: 'grup',
  met_eval: 'met_eval',
  part: 'part',
  per: 'per',
  prog: 'prog',
  rank_doc: 'rank_doc',
  sed: 'sed',
  sem: 'sem',
  tmp: 'tmp'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
